name: Oil Pulling Advisory Panel
favicon: null
layout_spectrum: 0.8532086117193103
typography_spectrum: 0.4690930761862546
title: The Oil Pulling Advisory Panel is a collaboration of healthcare professionals dedicated to reversing the trend towards deteriorating oral health
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#076b00'
    - '#00a7d1'
    - '#030303'
    - '#4c9447'
  brandStrength: 0.9375
  lightness: 0.9375
  saturation: 0.5
  rhythmicContrast: 1
purpose: []
